# Generated by Django 4.0.5 on 2022-07-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filho',
            old_name='taxa',
            new_name='subtotal',
        ),
    ]
